import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { notoSerif, notoSans } from "@/config/fonts";

export const metadata: Metadata = {
  title: "Origin Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${notoSans.variable} ${notoSerif.variable}`} lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
